### ISSUE TITLE
Enums excluded by a filter are not being excluded.

### ISSUE THREAD

**Issue by JakeSays** [dart-lang/ffigen#506] opened 2023-01-23 15:05 UTC
Given the header and ffigen config described below, I would expect the enum Foo to be excluded from the output, but it's not happening. It appears that `exclude:` on enums is being ignored. 

My ffigen version is 7.2.4.

foo.h:
```c
enum Foo
{
   one,
   two
};
```
foo.yaml:
```yaml
name: 'FooBindings'
output: 'lib/bindings/FooBindings.dart'
headers:
  entry-points:
    - 'foo.h'
enums:
  exclude:
    - Foo
```

**Comment by mannprerak2** [comment] 2023-01-29 08:34
Hi @JakeSays. I don't seem to be able to reproduce this (on `7.2.4`), are you sure you're running ffigen with
`dart run ffigen --config foo.yaml`.

**Comment by mannprerak2** [comment] 2023-02-04 16:25
Since I was unable to reproduce this, and also there's a [test](https://github.com/dart-lang/ffigen/blob/master/test/config_tests/include_exclude_test.dart) for this as well.

Closing this now, feel free to reopen, you can also attach the generated logs for us (with ` --verbose all` flag when running ffigen)

**Closed by mannprerak2** 2023-02-04 16:25 UTC

**Comment by JakeSays** [comment] 2023-02-04 21:11
@mannprerak2 hey sorry for the late reply. I'll investigate it again and see if it still happens.
