### ISSUE TITLE
How to transform ffi.Array<Uint8> to ffi.Point<Uint8>?????

### ISSUE THREAD

**Issue by fayfive** [dart-lang/ffigen#245] opened 2021-08-30 01:19 UTC
How to transform
@ffi.Array.multi([8])
external ffi.Array<ffi.Pointer<ffi.Uint8>> data;
 to
ffi.Pointer<ffi.Pointer<ffi.Uint8>> data

**Comment by dcharkes** [comment] 2021-08-30 06:33
duplicate of https://github.com/dart-lang/ffi/issues/117

**Closed by dcharkes** 2021-08-30 06:33 UTC
