### ISSUE TITLE
`ObjCBlock.fromFunction(closure)` indefinitely hangs on to closures and therefore leaks memory

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/ffigen#473] opened 2022-10-07 11:54 UTC
Right now the `ObjCBlock.fromFunction(closure)` is implemented as follows:
```dart
final _ObjCBlock_closureRegistry = <int, Function>{};
int _ObjCBlock_closureRegistryIndex = 0;

ffi.Pointer<ffi.Void> _ObjCBlock_registerClosure(Function fn) {
  final id = ++_ObjCBlock_closureRegistryIndex;
  _ObjCBlock_closureRegistry[id] = fn;
  return ffi.Pointer<ffi.Void>.fromAddress(id);
}

void _ObjCBlock_closureTrampoline(
    ffi.Pointer<_ObjCBlock> block, int arg0, ffi.Pointer<ffi.Bool> arg1) {
  return _ObjCBlock_closureRegistry[block.ref.target.address]!(arg0, arg1);
}

class ObjCBlock extends _ObjCBlockBase {
  ...
  /// Creates a block from a Dart function.
  ObjCBlock.fromFunction(
      AVFAudio lib, void Function(int arg0, ffi.Pointer<ffi.Bool> arg1) fn) 
      : this._(
            lib._newBlock1(
                ffi.Pointer.fromFunction<
                            ffi.Void Function(ffi.Pointer<_ObjCBlock> block,
                                NSUInteger arg0, ffi.Pointer<ffi.Bool> arg1)>(
                        _ObjCBlock_closureTrampoline)
                    .cast(),
                _ObjCBlock_registerClosure(fn)),
            lib);
  ...
}
```
This registers the closure in a global map where it's never removed from again - effectively creating a memory leak. Since the closures that are passed to `ObjCBlock.fromFunction(closure)` may hang on to non trivial amounts of memory, this seems like a big problem.

If memory is managed manually, it would mean calling `ObjCBlock.release()` should also release the closure from the map.

**Comment by liamappelbe** [comment] 2022-10-11 22:40
Duplicate of #428

**Closed by liamappelbe** 2022-10-11 22:40 UTC
