### ISSUE TITLE
Ffigen doesn't generate typedefs compatible with NativeCallable's APIs 

### ISSUE THREAD

**Issue by Piero512** [dart-lang/ffigen#614] opened 2023-09-03 17:16 UTC
Hello!

Today I was trying out the new [NativeCallable](https://api.dart.dev/stable/3.1.0/dart-ffi/NativeCallable-class.html) APIs and stumbled upon on a kinda annoying issue.

NativeCallable T generic parameter has this problem with ffigen that it requires specifying a function that only uses dart:ffi types, but there isn't currently a way to get one of these, since the generated typedefs usually come from pointer functions.

I think the NativeCallable API should not need to be changed, but say, a static function that removes the pointer and nativefunction from the signature would be useful? Although I do believe that the API should have bound T type to extend [NativeFunction](https://api.dart.dev/stable/3.1.0/dart-ffi/NativeFunction-class.html). 

I haven't checked if ffigen's config section functions -> expose-typedefs would generate the required typedefs, but if it does, it should be documented in the NativeCallable class too.

**Comment by liamappelbe** [comment] 2023-09-06 00:07
Ok, sounds like this is primarily a feature request for ffigen, so I've transferred the issue. The request is for ffigen to detect typedefs of function pointers, and define a second typedef that unwraps the `Pointer<NativeFunction<T>>` and just typedefs the `T` (which will be some `Function` type). Optionally, put this functionality behind a flag.

@Piero512 For issue (a), where the listener constructor isn't doing the type inference you expect, can you file a separate issue with code for this (back on the dart-lang/sdk repo)? Is this something that worked under `Pointer.fromFunction`, or is this a new feature request? I'm trying to get `NativeCallable` to fully replace all `Pointer.fromFunction` use cases. So if this inference works for `Pointer.fromFunction` then I'd consider it a regression if it doesn't also work for `NativeCallable`.

**Comment by Piero512** [comment] 2023-09-06 12:25
Hopefully I find some free time this week to create a minimum reproducible example for issue A, but then, if those typedefs would be generated, I am sure the issue A would become moot.

**Comment by dcharkes** [comment] 2023-09-18 10:19
@Piero512 @liamappelbe RE:https://github.com/dart-lang/ffigen/pull/621#discussion_r1326823516, do you have same examples of the use of the typedefs for both the pointers and the native functions? (In order to decide how common they are and what names to use.)

Maybe @mannprerak2 also has something to say about this, as he added the typedefs earlier.

```dart
typedef CXInclusionVisitor = ffi.Pointer<ffi.NativeFunction<CXInclusionVisitor>>;

typedef CXInclusionVisitor_function = ffi.Void Function(
    CXFile included_file,
    ffi.Pointer<CXSourceLocation> inclusion_stack,
    ffi.UnsignedInt include_len,
    CXClientData client_data);
```

vs (breaking change)

```dart
typedef CXInclusionVisitor_pointer = ffi.Pointer<ffi.NativeFunction<CXInclusionVisitor_function>>;

typedef CXInclusionVisitor = ffi.Void Function(
    CXFile included_file,
    ffi.Pointer<CXSourceLocation> inclusion_stack,
    ffi.UnsignedInt include_len,
    CXClientData client_data);
```

**Comment by mannprerak2** [comment] 2023-09-19 05:47
No input from my side, when we added typedefs, all the types were inline since I wasn't aware of such usecase.

As per the naming, maybe we should keep the name used by C intact, since C is exposing the typedef to a function pointer itself, but then we are further decomposing it to another typedef. This approach is also non breaking.

**Comment by dcharkes** [comment] 2023-09-19 09:07
Okay, maybe we should just land as is then.

**Closed** 2023-09-19 21:30 UTC
Labels: type-enhancement
