### ISSUE TITLE
Missing types without SEVERE message

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/ffigen#273] opened 2022-02-08 09:22 UTC
When commented out `compiler-opts` according to https://github.com/dart-lang/ffigen/issues/190#issuecomment-800778965, struct `io_service_t` and `mach_port_t` are missing

```diff
diff --git a/macos/IOKit.yaml b/macos/IOKit.yaml
index 9c7a916..0404501 100644
--- a/macos/IOKit.yaml
+++ b/macos/IOKit.yaml
@@ -1,9 +1,9 @@
 name: IOKit
 description: Bindings to `IOKit.h`.
 output: 'lib/src/macos/iokit.dart'
-compiler-opts: '-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Headers/'
+# compiler-opts: '-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Headers/'
 headers:
```

```diff
@@ -228,8 +228,6 @@ class IOHIDDeviceRef extends ffi.Opaque {}

 class CFAllocatorRef extends ffi.Opaque {}

-class io_service_t extends ffi.Opaque {}
-
 class CFStringRef extends ffi.Opaque {}

 class IOHIDManagerRef extends ffi.Opaque {}
@@ -238,8 +236,6 @@ class CFDictionaryRef extends ffi.Opaque {}

 class CFSetRef extends ffi.Opaque {}

-class mach_port_t extends ffi.Opaque {}
-
 const int kIOReturnSuccess = 0;

 const String kIOServicePlane = 'IOService';
```

# Reproduce

Repo: https://github.com/Sunbreak/logic_conf.dart
Branch: https://github.com/Sunbreak/logic_conf.dart/tree/reproduce/kernel-headers

```sh
% flutter2.0.x pub run ffigen --config macos/IOKit.yaml
Running in Directory: '/Users/sunbreak/Sunbreak/logic_conf.dart'
Input Headers: [macos/IOKit_.h]
Finished, Bindings generated in /Users/sunbreak/Sunbreak/logic_conf.dart/lib/src/macos/iokit.dart
```

# Envrionment

Flutter: Flutter 2.0.6
OS: Mac OS X 10.15.7

<details>
<summary>flutter doctor -v</summary>

```sh
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H1713 darwin-x64, locale en-CN)
    • Flutter version 2.0.6 at /Users/sunbreak/google/flutter-2.0.x
    • Framework revision 1d9032c7e1 (9 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[!] Connected device
    ! No devices available

! Doctor found issues in 5 categories.
```
</details>

**Comment by mannprerak2** [comment] 2022-02-08 10:11
If you are passing the headers manually via compiler-opts, you can try pass `false` for the key `compiler-opts-automatic -> macos -> include-c-standard-library` in your config.

**Comment by Sunbreak** [comment] 2022-02-08 12:06
Disabled `include-c-standard-library` like below

```diff
diff --git a/macos/IOKit.yaml b/macos/IOKit.yaml
index 0404501..8b72964 100644
--- a/macos/IOKit.yaml
+++ b/macos/IOKit.yaml
@@ -2,6 +2,9 @@ name: IOKit
 description: Bindings to `IOKit.h`.
 output: 'lib/src/macos/iokit.dart'
 # compiler-opts: '-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Headers/'
+compiler-opts-automatic:
+  macos:
+    include-c-standard-library: false
 headers:
   entry-points:
     - 'macos/IOKit_.h'
```

Results with

```sh
% flutter2.0.x pub run ffigen --config macos/IOKit.yaml
Running in Directory: '/Users/sunbreak/Sunbreak/logic_conf.dart.trial'
Input Headers: [macos/IOKit_.h]
[SEVERE] : Header macos/IOKit_.h: Total errors/warnings: 1.
[SEVERE] :     /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOTypes.h:60:10: fatal error: 'stdbool.h' file not found [Lexical or Preprocessor Issue]
Finished, Bindings generated in /Users/sunbreak/Sunbreak/logic_conf.dart.trial/lib/src/macos/iokit.dart
```

**Comment by mannprerak2** [comment] 2022-02-08 12:23
That's because you will need to explicitly mention the system header paths for ffigen if you disable this.

Why exactly are you expecting SEVERE errors in this case? since ffigen will only generate what is required by your entry-points and include directive header files for these system headers.

**Comment by Sunbreak** [comment] 2022-02-08 12:29
Because `Pointer<io_service_t>` and `Pointer<mach_port_t>` becomes `int` at [commit of branch `reproduce/kernel-headers`](https://github.com/Sunbreak/logic_conf.dart/commit/deee7d6ad8ffb47098b05b4c7e97900e6bea5888)

```diff
@@ -177,7 +177,7 @@ class IOKit {
       _IOHIDManagerCopyDevices_ptr.asFunction<_dart_IOHIDManagerCopyDevices>();

   int IOObjectRelease(
-    ffi.Pointer<io_service_t> object,
+    int object,
   ) {
     return _IOObjectRelease(
       object,
@@ -189,8 +189,8 @@ class IOKit {
   late final _dart_IOObjectRelease _IOObjectRelease =
       _IOObjectRelease_ptr.asFunction<_dart_IOObjectRelease>();

-  ffi.Pointer<io_service_t> IORegistryEntryFromPath(
-    ffi.Pointer<mach_port_t> masterPort,
+  int IORegistryEntryFromPath(
+    int masterPort,
     ffi.Pointer<ffi.Int8> path,
   ) {
     return _IORegistryEntryFromPath(
```

Which is wrong and couldn't pass test

**Comment by mannprerak2** [comment] 2022-02-08 12:33
Got it, I'll try to find what's causing this behaviour.

**Comment by Sunbreak** [comment] 2022-02-08 12:43
BTW under `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Headers`

- `mach_port_t` is defined in `sys/_types/_mach_port_t.h`

```c
#ifndef _MACH_PORT_T
#define _MACH_PORT_T
#include <sys/_types.h> /* __darwin_mach_port_t */
typedef __darwin_mach_port_t mach_port_t;
#endif /* _MACH_PORT_T */
```

- `io_object_t` is defined in `device/device_types.h`

```c
#ifndef __IOKIT_PORTS_DEFINED__
#define __IOKIT_PORTS_DEFINED__
typedef mach_port_t     io_object_t;
#endif  /* __IOKIT_PORTS_DEFINED__ */
```

- `io_service_t` is defined in `IOKit/IOTypes.h`

```c
#include <device/device_types.h>

typedef io_object_t     io_connect_t;
typedef io_object_t     io_enumerator_t;
typedef io_object_t     io_iterator_t;
typedef io_object_t     io_registry_entry_t;
typedef io_object_t     io_service_t;
typedef io_object_t     uext_object_t;
```

These are not C standard library. And I don't think `include-c-standard-library: false` works

**Comment by Sunbreak** [comment] 2022-02-08 12:51
FYI the Mac mini is a clean re-install Mac OS X 10.15.7, without Xcode, only Command Line Tools

# Environment

- flutter doctor -v

```sh
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
```

- brew config

```sh
HOMEBREW_VERSION: 3.3.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8a787e45ff45583fb245030757296548f82c1cbd
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2024e2d006e967845e827f9451723dfe44c37cf3
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

- brew doctor

```sh
Your system is ready to brew.
```

- xcode-select -p

```sh
/Library/Developer/CommandLineTools
```

# Caution

```sh
% ls -l /Library/Developer/CommandLineTools/SDKs
total 0
lrwxr-xr-x  1 root  wheel   14 Feb  7 16:07 MacOSX.sdk -> MacOSX11.1.sdk
drwxr-xr-x  8 root  wheel  256 Jul 10  2020 MacOSX10.15.sdk
drwxr-xr-x  7 root  wheel  224 Nov 30  2020 MacOSX11.1.sdk
```

## There are two versions of MacOSX.sdk and `MacOSX.sdk` is soft linked to MacOSX11.1sdk, while `ffigen` seems to use MacOSX10.15.sdk

**Comment by mannprerak2** [comment] 2022-02-09 15:56
I tried reproducing this.

There are no `SEVERE` parsing errors, so that means ffigen is getting the right headers and all the definitions required.

I am not sure why you are expecting `ffi.Pointer<io_service_t> object` to be generated, since your function argument is `io_object_t object`. And this type is eventually mapped to an int -

```yaml
typedef io_object_t = mach_port_t;
typedef mach_port_t = __darwin_mach_port_t;
typedef __darwin_mach_port_t = __darwin_mach_port_name_t;
typedef __darwin_mach_port_name_t = __darwin_natural_t;
typedef __darwin_natural_t = pkg_ffi.UnsignedInt;
```

**Comment by Sunbreak** [comment] 2022-02-09 16:17
But it was `ffi.Pointer<io_service_t>` before the commit of https://github.com/Sunbreak/logic_conf.dart/tree/reproduce/kernel-headers

```diff
@@ -189,8 +189,8 @@ class IOKit {
   late final _dart_IOObjectRelease _IOObjectRelease =
       _IOObjectRelease_ptr.asFunction<_dart_IOObjectRelease>();

-  ffi.Pointer<io_service_t> IORegistryEntryFromPath(
-    ffi.Pointer<mach_port_t> masterPort,
+  int IORegistryEntryFromPath(
+    int masterPort,
     ffi.Pointer<ffi.Int8> path,
   ) {
     return _IORegistryEntryFromPath(
```

```diff
@@ -228,8 +228,6 @@ class IOHIDDeviceRef extends ffi.Opaque {}

 class CFAllocatorRef extends ffi.Opaque {}

-class io_service_t extends ffi.Opaque {}
-
 class CFStringRef extends ffi.Opaque {}

 class IOHIDManagerRef extends ffi.Opaque {}
@@ -238,8 +236,6 @@ class CFDictionaryRef extends ffi.Opaque {}

 class CFSetRef extends ffi.Opaque {}

-class mach_port_t extends ffi.Opaque {}
-
 const int kIOReturnSuccess = 0;

 const String kIOServicePlane = 'IOService';
```

And it passes test

**Comment by mannprerak2** [comment] 2022-02-09 16:21
Can you still generate the same bindings on your machine using the older ffigen version?

**Comment by Sunbreak** [comment] 2022-02-09 16:24
Yep. It generates

- `ffi.Pointer<io_service_t>` with `compiler-opts: '-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Headers/'`
- `int` without `compiler-opts`

**Comment by Sunbreak** [comment] 2022-02-09 16:51
A similiar issue is [Update HANDLE & HWND with win32](https://github.com/Sunbreak/logic_conf.dart/commit/1888bac8d4739c68c2eda83359293921a3821739) on https://github.com/Sunbreak/logic_conf.dart/tree/wip/win32-type-map

Without `type-map`, `HANDLE` and `HWND` are `Pointer`/`Opaque`

When taking advantage of `package:win32`, `HANDLE` and `HWND` are `int`/`IntPtr`

**Comment by Sunbreak** [comment] 2022-02-09 17:09
Posted https://github.com/timsneath/win32/issues/363

**Comment by mannprerak2** [comment] 2022-02-09 18:06
When supplying the compiler-opts, I am able to generate this correctly(Although I get some SEVERE warnings due to issues with system headers)

```
  int IOObjectRelease(
    io_object_t object,
  )
typedef io_object_t = ffi.Pointer<OSObject>;
class OSObject extends ffi.Opaque {}
```

But without it, when using system header it uses different headers which do infact map up to `int`. I printed the exact file paths for this -
```
[FINE]   :   getCodeGenType (Type) spelling: io_object_t, kind: 107, kindSpelling: Typedef
/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOTypes.h
[FINE]   :   getCodeGenType (Type) spelling: mach_port_t, kind: 107, kindSpelling: Typedef
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_mach_port_t.h
[FINE]   :   getCodeGenType (Type) spelling: __darwin_mach_port_t, kind: 107, kindSpelling: Typedef
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types.h
[FINE]   :   getCodeGenType (Type) spelling: __darwin_mach_port_name_t, kind: 107, kindSpelling: Typedef
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types.h
[FINE]   :   getCodeGenType (Type) spelling: __darwin_natural_t, kind: 107, kindSpelling: Typedef
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/arm/_types.h
[FINE]   :   getCodeGenType (Type) spelling: unsigned int, kind: 9, kindSpelling: UInt
```

So it's not that ffigen is not printing severe headers, it's just that these have been defined like this in the default paths printed above.

**Comment by Sunbreak** [comment] 2022-02-10 02:58
Mine Mac mini is a clean re-install Catalina without Xcode

So which is a preferred way?

- Include C Headers from Xcode or Command Line Tools?
- Use `compiler-opts` or not?
- Use `Pointer` or `UnsignedLong`/`Uint32` or `IntPtr`?

**Comment by mannprerak2** [comment] 2022-02-10 04:57
Well I'm not sure about this. But imo

- The headers you use should correspond to the dynamic libraries you are using.
- compiler-opts are just a way to specify the exact path of system headers to use, and I think you should definitely use it if you intend to generate system headers.
- Pointer/Unsigned Long/IntPtr may work interchangeably on the specific platform you are trying to build, but they are not the same thing, so you should let these types be decided by the header files itself.

I'll close this issue now, since this is not exactly related to ffigen.

**Closed by mannprerak2** 2022-02-10 04:57 UTC
